# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
---
name: thinkbook-testimg
description: Office productivity image for Lenovo ThinkBook T14 ACL G3 with Ryzen 5700U

base-image: ghcr.io/ublue-os/kinoite-main
image-version: 43

modules:
  - type: dnf
    install:
      packages:
        - fprintd
        - fprintd-pam
        - libfprint
        - fwupd
        - power-profiles-daemon
        - hunspell
        - hunspell-en-US
        - hunspell-de
        - godot
        - htop
        - neofetch
        - vim-enhanced

    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - scope: system
        notify: true
        repo:
          title: Flathub (system)
        install:
          # Browser - Floorp as Flatpak (reliable)
          - one.ablaze.floorp
          # Office Suite
          - org.onlyoffice.desktopeditors
          # Gaming
          - com.valvesoftware.Steam
          # Productivity
          - org.gnome.Calculator
          - org.gnome.Calendar
          - org.gnome.Contacts
          - org.gnome.clocks
          # Utilities
          - org.gnome.FileRoller
          - com.github.tchx84.Flatseal
          - io.github.flattool.Warehouse
          - io.missioncenter.MissionCenter
          # Media
          - org.videolan.VLC
          - org.gnome.Loupe
          - org.gnome.Evince
          - org.gnome.Notes

      - scope: user
        repo:
          title: Flathub (user)

  - type: signing